# Main navigation menu
[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Photos"
  pageRef = "photos"
  weight = 20

[[main]]
  name = "Awesome Stuff"
  pageRef = "awesome_stuff"
  weight = 30

[[main]]
  name = "PGP Keys"
  pageRef = "pgp-keys"
  weight = 40

[[main]]
  name = "About"
  pageRef = "/"
  weight = 50

# Footer menu
[[footer]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/christopherjbutler/"
  weight = 10

[[footer]]
  name = "GitHub"
  url = "https://github.com/butler54"
  weight = 20
