baseURL = 'https://chris.thebutlers.me'
languageCode = 'en-us'
title = "Chris's Blog"

enableRobotsTXT = true
[pagination]
  pagerSize = 10
summaryLength = 30

# Hugo Modules configuration
[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"

[imaging]
  resampleFilter = "CatmullRom"
  quality = 85
  anchor = "smart"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    lineNos = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
